# Generated by Django 6.0.2 on 2026-02-20 09:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('id_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='loans_clien_name_c625c3_idx'), models.Index(fields=['phone_number', 'id_number'], name='loans_clien_phone_n_9bd4ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], db_index=True, default='ACTIVE', editable=False, max_length=10)),
                ('due_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='loans.client')),
            ],
        ),
        migrations.CreateModel(
            name='LoanReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('DUE_SOON', 'Due Soon'), ('OVERDUE', 'Overdue')], max_length=12)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='loans.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mpesa_receipt', models.CharField(db_index=True, max_length=50, unique=True)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('paid_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.loan')),
            ],
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status', 'due_date'], name='loans_loan_status_196efd_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['client', 'status'], name='loans_loan_client__a27993_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['created_at', 'status'], name='loans_loan_created_481a4c_idx'),
        ),
        migrations.AddIndex(
            model_name='loanreminderlog',
            index=models.Index(fields=['reminder_type', 'sent_at'], name='loans_loanr_reminde_b889da_idx'),
        ),
        migrations.AddIndex(
            model_name='loanreminderlog',
            index=models.Index(fields=['loan', 'sent_at'], name='loans_loanr_loan_id_bd335f_idx'),
        ),
        migrations.AddConstraint(
            model_name='loanreminderlog',
            constraint=models.UniqueConstraint(fields=('loan', 'reminder_type'), name='unique_loan_reminder_type'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['loan', 'paid_at'], name='loans_payme_loan_id_87d802_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['phone', 'paid_at'], name='loans_payme_phone_ff1dff_idx'),
        ),
    ]
