# Generated by Django 6.0.2 on 2026-02-20 10:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(db_index=True, max_length=120)),
                ('action', models.CharField(max_length=255)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('otp_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS')], max_length=10)),
                ('message', models.TextField()),
                ('success', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=1)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'permissions': [('can_approve_loan', 'Can approve loan')]},
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='loans_clien_phone_n_9bd4ae_idx',
        ),
        migrations.AddField(
            model_name='client',
            name='credit_score',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='id_number_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='client',
            name='id_number_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='max_loan_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='raw_payload_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['phone_number', 'credit_score'], name='loans_clien_phone_n_58dc89_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['approval_status', 'created_at'], name='loans_loan_approva_4dcada_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['mpesa_receipt', 'paid_at'], name='loans_payme_mpesa_r_2bcdb0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at', 'status_code'], name='loans_audit_created_599adf_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor', 'created_at'], name='loans_audit_actor_9d7f83_idx'),
        ),
        migrations.AddField(
            model_name='clientaccesstoken',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='loans.client'),
        ),
        migrations.AddIndex(
            model_name='clientotp',
            index=models.Index(fields=['phone_number', 'created_at'], name='loans_clien_phone_n_a3c204_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['success', 'created_at'], name='loans_notif_success_7d4bbe_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['phone_number', 'created_at'], name='loans_notif_phone_n_c8f599_idx'),
        ),
        migrations.RemoveField(
            model_name='client',
            name='id_number',
        ),
    ]
