# Generated by Django 6.0.2 on 2026-02-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_auditlog_clientaccesstoken_clientotp_notificationlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=80)),
                ('reference', models.CharField(db_index=True, max_length=120)),
                ('severity', models.CharField(db_index=True, default='MEDIUM', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category', 'created_at'], name='loans_suspi_categor_18ec0f_idx'), models.Index(fields=['resolved', 'created_at'], name='loans_suspi_resolve_3a774f_idx')],
            },
        ),
    ]
