"""
Django settings for weito_backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-dev-only-secret-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = [host.strip() for host in os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if host.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'loans.apps.LoansConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'loans.middleware.AuditLogMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'weito_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'weito_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
}

MPESA_ENVIRONMENT = os.getenv('MPESA_ENVIRONMENT', 'sandbox').lower()
MPESA_BASE_URL = (
    'https://sandbox.safaricom.co.ke'
    if MPESA_ENVIRONMENT == 'sandbox'
    else 'https://api.safaricom.co.ke'
)
MPESA_CONSUMER_KEY = os.getenv('MPESA_CONSUMER_KEY', '')
MPESA_CONSUMER_SECRET = os.getenv('MPESA_CONSUMER_SECRET', '')
MPESA_SHORTCODE = os.getenv('MPESA_SHORTCODE', '')
MPESA_PASSKEY = os.getenv('MPESA_PASSKEY', '')
MPESA_CALLBACK_BASE_URL = os.getenv('MPESA_CALLBACK_BASE_URL', 'http://127.0.0.1:8000')
MPESA_CALLBACK_TOKEN = os.getenv('MPESA_CALLBACK_TOKEN', 'replace-with-secure-token')
MPESA_WEBHOOK_SECRET = os.getenv('MPESA_WEBHOOK_SECRET', '')
MPESA_CALLBACK_ALLOWED_IPS = [
    ip.strip() for ip in os.getenv('MPESA_CALLBACK_ALLOWED_IPS', '').split(',') if ip.strip()
]

SMS_PROVIDER = os.getenv('SMS_PROVIDER', 'twilio')
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN', '')
TWILIO_FROM_NUMBER = os.getenv('TWILIO_FROM_NUMBER', '')
TWILIO_WHATSAPP_FROM_NUMBER = os.getenv('TWILIO_WHATSAPP_FROM_NUMBER', '')
ENABLE_WHATSAPP_REMINDERS = os.getenv('ENABLE_WHATSAPP_REMINDERS', 'False').lower() == 'true'

FIELD_ENCRYPTION_KEY = os.getenv('FIELD_ENCRYPTION_KEY', '')
DATA_HASH_SALT = os.getenv('DATA_HASH_SALT', SECRET_KEY)
SYSTEM_AUTOMATION_TOKEN = os.getenv('SYSTEM_AUTOMATION_TOKEN', 'replace-system-token')
DB_BACKUP_DIR = os.getenv('DB_BACKUP_DIR', str(BASE_DIR / 'backups'))

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'weito-backend-cache',
        'TIMEOUT': 300,
    }
}

CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

CELERY_BEAT_SCHEDULE = {
    'send-due-soon-reminders-daily': {
        'task': 'loans.tasks.send_due_soon_reminders',
        'schedule': crontab(hour=8, minute=0),
    },
    'send-overdue-reminders-daily': {
        'task': 'loans.tasks.send_overdue_reminders',
        'schedule': crontab(hour=9, minute=0),
    },
    'recompute-credit-scores-nightly': {
        'task': 'loans.tasks.recompute_credit_scores_task',
        'schedule': crontab(hour=1, minute=0),
    },
    'daily-database-backup': {
        'task': 'loans.tasks.run_daily_backup',
        'schedule': crontab(hour=2, minute=0),
    },
    'daily-reconciliation': {
        'task': 'loans.tasks.reconcile_transactions',
        'schedule': crontab(hour=3, minute=0),
    },
    'retry-failed-notifications': {
        'task': 'loans.tasks.retry_failed_notifications',
        'schedule': crontab(minute='*/30'),
    },
}
